import Head from "next/head";
import FoodAnalyzePage from "./food";

export default function Home() {
  return (
    <>
      <Head>
        <title>오빠레시피</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FoodAnalyzePage />
    </>
  );
}

(Home as any).title = "오빠레시피";
(Home as any).showBackButton = false;